### ISSUE TITLE
derived quantities for negative binomial

### ISSUE THREAD

**Issue by eborgman** [lzachmann/models-for-missing-data#16]
@lzachmann When you're back from vacation and get to the derived quantities for the negative binomial model and ordinal latent model, here's some additional info. You might not need this, but in case it's helpful, here are my errors when running the 1) negative binomial model with derived quantities on and the 2) ordinal latent model with derived quantities on

1) neg binomial

![image](https://user-images.githubusercontent.com/25830271/142231218-41ce1634-ee72-4420-a3f5-d952281790e0.png)

run traceback()

![image](https://user-images.githubusercontent.com/25830271/142231250-9e0cc29b-141c-4082-bb8d-9cd2999b5b3b.png)

![image](https://user-images.githubusercontent.com/25830271/142231272-ae229f58-e7b7-4dd1-bd1d-02af6e8c68b8.png)

2) And the ordinal latent model
![image](https://user-images.githubusercontent.com/25830271/142232955-d96dbe66-bb47-4b88-a67e-549e974ef300.png)

run traceback()
![image](https://user-images.githubusercontent.com/25830271/142233097-aa3942df-f38d-4860-897e-a49164a37421.png)

![image](https://user-images.githubusercontent.com/25830271/142233164-18272414-8f13-46fd-93e5-416e3f3e3555.png)

**Comment by lzachmann** [comment]
Hey Erin, re: item 1, would you mind trying to run `negative-binomial-simple` in the likelihood block of your analysis YAML (with or without the derived quantities)? 

```yml
likelihood:
    # - poisson
    # - negative-binomial
    - negative-binomial-simple
```

`negative-binomial-simple` is the older version of the negative binomial model and might just work. I'll have to take a closer look at item 2.

**Comment by lzachmann** [comment]
> `negative-binomial-simple` is the older version of the negative binomial model and might just work.

The newer version of the negative binomial model (as yet incomplete) uses a moment match for kappa, which gives us greater flexibility with the variance in those models (e.g., the use of proper hierarchical site-level variances and not a simple, fixed stratum-level kappa term). You may find that the old version of the negative binomial (abbreviated `nb-vanilla`, I think, in the model outputs) works well enough for GRKO....

**Comment by eborgman** [comment]
I ran nb-vanilla with derived quantities on.  (assets/uplands-output/ROMN/GRKO/species-richness/all.rich/nb-vanilla_exp_none_hier-site/botanist-ja_mgmtzone-deflections) The strata-level inference works and then gets an error at site-level.

![image](https://user-images.githubusercontent.com/25830271/142487403-e0f7b011-deb9-449c-9a72-89bf0650b5e7.png)

That error looks very familiar. I think I saw it the other day when trying to re-run a zero-inflated-nb for the relative cover models... If it's the same error, I might have broken something that's causing this error. I've got another meeting now but will look more into it. Does no "x.pred.raw" mean anything to you?

**Comment by lzachmann** [comment]
Sorry Erin I too saw this and was hoping to beat you to the punch. No such luck. I've got this fixed locally, and perhaps your ordinal latent normal model issue as well. Testing and will push the changes to the main branch as soon as I can confirm it's working.

**Comment by lzachmann** [comment]
Hey @eborgman I pushed some changes to the `gh-submodule` here: https://gitlab.com/nps-ima/uplands-ci/-/tree/gh-submodule. I forget the exact process we followed to get you 'synced' with the latest. Note that -- at least the way things are currently structured -- the finite population case works only for models specified with covariates. I believe this is how it used to be as well....

**Comment by eborgman** [comment]
Both the negative binomial and the ordinal latent model are up and running with derived quantities! Closing discussion.
