### ISSUE TITLE
zi neg binomial model bug

### ISSUE THREAD

**Issue by eborgman** [lzachmann/models-for-missing-data#21]
@lzachmann 
This is the bug I mentioned earlier today. 
Using config "rel-cover"
Model assets/uplands-output/ROMN/GRKO/rel-cover/NumberBlueGramaHits/zero-inflated-beta-binomial_inv-logit_none_hier-site/botanist-ja_mgmtzone-deflections

The model starts running fine and gets hung up

![image](https://user-images.githubusercontent.com/25830271/145473295-5e5cb168-9c33-4899-bcf6-3c63a0229348.png)

Traceback
![image](https://user-images.githubusercontent.com/25830271/145473880-cf213ebe-da9d-49ea-b69e-f60df4c0ca87.png)

**Comment by lzachmann** [comment]
Fixed with latest batch of commits.
