### ISSUE TITLE
betas varying by stratum

### ISSUE THREAD

**Issue by eborgman** [lzachmann/models-for-missing-data#6]
@lzachmann Can you please refresh my memory what's been developed to allow the Betas to vary by stratum? I believe you developed something for Cheryl, right? Is that functionality in the latest pipeline and/or set up for others to use? I'm not sure if I want to incorporate that into the current report I'm working on, but I'm considering it.

**Comment by lzachmann** [comment]
Hey @eborgman excellent timing. The basic reasoning, including a crude computational 'proof' can be seen here: https://gitlab.com/nps-ima/uplands-ci/-/issues/166. I will try to migrate that material to this issue when I have a little time. 

TL;DR I think we've shown that we can use the existing code to do exactly what we need, even if &ndash; under the hood &ndash; it's somewhat abstruse mathematically. We can use derived quantities to get the inference we want.
